Adds tap document to project
fga-eps-mds/2021-2-MeasureSoftGram-Doc pull request #1
Opened 2022-02-15 01:53 UTC by thiagolopess

This Pull Request inserts the Project Charter into the repository

2022-02-15 11:23 UTC, igor-paiva requested changes

2022-02-15 11:23 UTC, igor-paiva commented on docs/artefato/tap.md
> +| 1.0    | 14/02/2022 | Criação do termo de Abertura do proejto | - | Igor Paiva, Renan Cristyan, Rhuan Queiroz, Thiago Lopes |
Typo: "proejto"

2022-02-15 11:23 UTC, igor-paiva commented on docs/artefato/tap.md
> +| Versão | Data       | Modificação                    | Motivo | Autor |
Wouldn't be more appropriate to use "autores" or "autor(es)"

2022-02-17 18:30 UTC, igor-paiva submitted a review, later dismissed

2022-02-18 01:10 UTC, RCristyan approved these changes
LGTM

2022-02-18 01:12 UTC, merged